dapr/community

.github/ISSUE_TEMPLATE/membership.md
README.md
community-membership.md

Update gitter to discord

---

community-membership.md
steering-and-technical-committee-charter.md
technical-and-steering-committee-charter.md

This is the bootstrap for the Technical and Steering Committee for Dapr

Steering & Technical Committee charter

---

MAINTAINERS.md

This is a list of all maintainers in the dapr repos

Adding list of maintainers

---

README.md

added community call instances through March 2022, reverting back to 10am PST schedule.

added community call instances through March 2022

---

steering-and-technical-committee-charter.md

Signed-off-by: msfussell <markfussell@gmail.com>

adding Discord Admin status

---

ADOPTERS.md
MAINTAINERS.md
README.md
community-membership.md
steering-and-technical-committee-charter.md

Updating 
- list of Dapr Maintainers
- adding new Community Call dates
- Resolving issue https://github.com/dapr/community/issues/41
- Adding Microsoft members to STC as per STC vote on 14th Dec 2021

Updates due to issues and STC Membership

---

ADOPTERS.md

Update adopters list

---

steering-and-technical-committee-charter.md

Signed-off-by: Mark Fussell <markfussell@gmail.com>
Updating orgs for mfussell and yschneider

updating org names

---

MAINTAINERS.md

Add Bernd as maintainer to python-sdk.

---

README.md

Remove Thursday sync schedule.

---

ADOPTERS.md

Signed-off-by: Paul Yuknewicz <paulyuk@microsoft.com>

Updating adopters: Microsoft Azure

---

.github/ISSUE_TEMPLATE/community-call-agenda.md
README.md

Signed-off-by: msfussell <markfussell@gmail.com>
Also updating the list of community meeting dates until Sept 2022

new community agenda template

---

MAINTAINERS.md

Update current company for maintainers and sort it alphabetically.

---

README.md

Adding a public calendar for the community calls

Adding public calendar

---

README.md

Signed-off-by: Sky Ao <aoxiaojian@gmail.com>

add China community website and meeting information

---

README.md

Move community calls to Wednesdays 9am PST as agreed by STC.

---

DaprCon/2022/proposal-submission-form.md

Add DaprCon date to post

---

ADOPTERS.md

Signed-off-by: Paul Yuknewicz <paulyuk@microsoft.com>
Thank you for submissions!

Syncing adopters.md with Are You Using Dapr post submissions

---

.github/ISSUE_TEMPLATE/sandbox-admission.md
.github/ISSUE_TEMPLATE/sandbox-graduation.md

Template for admission and graduation in dapr-sandbox.

---

steering-and-technical-committee-charter.md

Update committee members

---

ADOPTERS.md

Update missing links in adopters lists

Update missing links in adopters lists

---

MAINTAINERS.md

Adding Amulya as maintainer.

---

README.md

Update dates for future community calls

---

README.md

Update community call dates

---

README.md

Added form to allow speakers to send over topics for the community call

Added Community Call form

---

release-process.md

Signed-off-by: greenie-msft <56556602+greenie-msft@users.noreply.github.com>

Remove K8s references

---

README.md

Signed-off-by: greenie-msft <56556602+greenie-msft@users.noreply.github.com>

Add release planning information to readme

---

README.md

Signed-off-by: greenie-msft <56556602+greenie-msft@users.noreply.github.com>

Update readme to reflect accurate community call schedules

---

ADMINISTRATORS.md
steering-and-technical-committee-charter.md

Define the administrator role and its rules.

---

README.md

update to cncf zoom link

---

README.md

Add zoom passcode for milestone call

---

README.md

Signed-off-by: Artur Souza <artur.barbalho@outlook.com>

Use single Zoom link.

---

README.md

Signed-off-by: YesYouKen <kennethtxytqw@users.noreply.github.com>

documentation: fix reference

---

ADMINISTRATORS.md

Signed-off-by: Artur Souza <asouza.pro@gmail.com>
Closes: #273

Adding Artur as administrator.

---

COMMUNITY-MANAGER.md

This addresses this issue https://github.com/dapr/community/issues/284

 Community Manager Role

---

COMMUNITY-MANAGER.md

Timezones for Nyemade and myself were swapped.
Added _manage Twitter_ account to the community manager duties.

Fix timezones, add Twitter

---

.github/ISSUE_TEMPLATE/community-call-agenda.md
README.md

As discussed with @greenie-msft and @nyemade-uversky during a sync call yesterday: 
- Added a rotating schedule to host the community calls.
- Added checklists for the host to ensure a clear process
Once this PR has been merged I'll create more Community call issues that uses this new format.

Community call process

---

elections/2023-STC/voter-guide.md

Adding voter guide for 2023 STC elections.

Add voter guide

---

elections/2023-STC/candidate-yaron2.md

Fix typos in candidate doc

---

README.md

New milestone sync time

---

elections/2023-STC/voters.yaml

Added - ancientitguy, Kai Walter

Gstevens addvoter1

---

MAINTAINERS.md

See https://github.com/dapr/community/issues/430

Add Cecil Phillip (community manager)

---

community-manager-onboarding-1.md

Signed-off-by: Marc Duiker <marcduiker@users.noreply.github.com>

Update GitHub and Discord onboarding

---

COMMUNITY-MANAGER.md
MAINTAINERS.md

#434 
Signed-off-by: Marc Duiker <marcduiker@users.noreply.github.com>

Add Annu as CM

---

steering-and-technical-committee-charter.md

@daixiang0 was misspelt on the STC charter

fix: update broken/incorrect username for daixiang0 on the STC charter

---

COMMUNITY-MANAGER.md

Update CM term and add reviewing of community content

---

blogposts/README.md
presentations/README.md

Add new blogs and presentation contributions

Add new blogs and presentation contributions

---

ADMINISTRATORS.md

Closes https://github.com/dapr/community/issues/464

Update admin term to 2y.

---

blogposts/README.md
presentations/README.md

- [Dapr with Score and Humanitec — Improving the Developer Experience of your Platform, on steroids!](https://medium.com/@mabenoit/dapr-with-score-and-humanitec-developer-experience-with-your-platform-on-steroids-a848f2de0a5a)
- [Dapr + Score + Humanitec demo](https://www.youtube.com/watch?v=4gT0Y6QxinU&t=140s)
- [Dapr + Score: Crafting and improving your developers experience](https://platformcon.com/talks/dapr-score-crafting-and-improving-your-developers-experience)

Add Dapr+Score+Humanitec blog post and presentations

---

steering-and-technical-committee-meetings/README.md

Fix code of conduct, update link to past meetings for STC.

chore: Update README.md

---

presentations/README.md

Added presentation from AppDeveloperCon NA 2024

---

README.md

An intended section link refer to upcoming dates in list.

docs(README): section link upcoming dates

---

presentations/README.md

Adding my talk about Dapr and Cilium from KCD Denmark last year

Add KCD Denmark 2024 Talk

---

MAINTAINERS.md

Add Elena Kolevska as maintainer

---

presentations/README.md

Add presentation - Microsoft Reactor São Paulo - @waltercoan
Signed-off-by: Walter Silvestre Coan <walter.coan@gmail.com>

Add presentation - Microsoft Reactor São Paulo - @waltercoan

---

MAINTAINERS.md

Add artur-ciocanu as maintainer

---

MAINTAINERS.md

Remove mukundansundar as maintainer
